config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :show]

  resources :bands
  resources :albums, except: :index
  resources :tracks, except: :index

end

app/models/album.rb
class Album < ActiveRecord::Base

  attr_reader :name

  belongs_to(
    :band,
    class_name: "Band",
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    class_name: "Track",
    foreign_key: :track_id,
    primary_key: :id,
    dependent: :destroy
  )

end

app/models/band.rb
class Band < ActiveRecord::Base

  attr_reader :name

  has_many(
    :albums,
    class_name: "Album",
    foreign_key: :band_id,
    primary_key: :id,
    dependent: :destroy
  )

end

app/models/track.rb
class Track < ActiveRecord::Base

  attr_reader :name

  belongs_to(
    :album,
    class_name: "Album",
    foreign_key: :album_id,
    primary_key: :id
  )

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true

  validates( :password, length: {minimum: 6, allow_nil: true} )


  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.base64
  end

  def self.is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
    #might need to be self.password_digest
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    return user if User.is_password?(password)
    nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
    # session[session_token] = self.session_token
    # do I need to set the session[session_token] here?
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.base64
    # again, need to set session_token in cookies?
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end





end #user class

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :logged_in?
  helper_method :my_link_to

  include ApplicationHelper

  def current_user
    return nil unless session[:session_token]
    User.find_by(session_token: session[:session_token])
    #this find_by might not work right
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out_user!(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  def my_link_to(body, url)

    <<-HTTP.html_safe
    <a href="#{url}">#{body}</a>
    HTTP
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create #login
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Incorrect email and/or password"]
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(user.id)
    end
  end

  def destroy #log out
    user = User.find_by(session_token: session[:session_token])
    log_out_user!(user)
    redirect_to new_session_url
  end

  private


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create #sign up a new user
    @user = User.new(user_params)
    @user.password=(user_params[:password])
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user.id)
    else
      flash.now[:errors] = @user.errors.full_messages
      #don't forget to implement this in html
      render :new
    end
  end

  def new #render signup page, persisting data after errors
    @user = User.new
    render :new
  end

  def show
    render :show
  end


  def user_params
    params.require(:user).permit(:email, :password)
    #do i need a session token here? seems like i would
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def list_items(items)

    list = ""
    items.each do |item|
      list+=
      "<li>
          #{item}
      </li>"
    end

    "<ul>" + list + "</ul>"

  end


end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/band/index.html.erb
<h1>Your Bands</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <!-- fix these illegal link_to -->
    <% if current_user.nil? %>
      <%= my_link_to("Sign in", new_session_url) %>
       or
      <%= my_link_to "Sign up", new_user_url %>
    <% else %>
      <%= current_user.email %>
      <%= button_to "Logout", session_url, method: :delete %>
    <% end %>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>New Users</h1>

<%= render "shared/errors" %>

<form action="<%= users_url.html_safe %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="user_email">Email</label>
  <input type="text"
          name="user[email]"
          id="user_email"
          value="">
  <label for="password">Password</label>
  <input type="password"
          name="user[password]"
          id="user_password"
          value="">

  <input type="submit" value="Sign up">
</form>

app/views/users/show.html.erb
<h1>Not much to see.</h1>